DROP SCHEMA IF EXISTS CALORIZER;

CREATE SCHEMA CALORIZER;
USE CALORIZER;

CREATE TABLE USERS (
    ID INT NOT NULL AUTO_INCREMENT,
    EMAIL VARCHAR(200) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE INDEX EMAIL (EMAIL)
) COLLATE='utf8_general_ci' ENGINE=InnoDB AUTO_INCREMENT=1;
 
CREATE TABLE INGREDIENTS (  
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(200) NOT NULL,
    CALORIES DEC (5, 1) NOT NULL,
    CARBS DEC (4, 1) NOT NULL,
    FATS DEC (4, 1) NOT NULL,
    PROTEINS DEC (4, 1) NOT NULL,
    PRIMARY KEY (ID),
) COLLATE='utf8_general_ci' ENGINE=InnoDB;